---
title: "Analysis of government trust and attitude to vaccines"
author: "Spring"
date: "3/29/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)

ed_levels <- c(
  "Primary school",
  "Secondary school (age under 15 years old)",
  "GNVQ / GSVQ / GCSE/ SCE standard.",
  "NVQ1, NVQ2",
  "NVQ3/ SCE Higher Grade/ Advanced GNVQ/ GCE A/AS or similar.",
  "NVQ4 / HNC / HND / Bachelor's degree or similar.",
  "NVQ5 or post-graduate diploma."
)

likert_levels <- c("Strongly disagree", 
  "Tend to disagree", 
  "Neither agree nor disagree", 
  "Tend to agree", 
  "Strongly agree")                      
                
d_trustvac <- read_csv(
  '../data/trust-vaccines.csv',
  col_types = cols(
    col_number(),
    col_factor(),
    col_factor(ordered = TRUE, levels = ed_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
    col_factor(ordered = TRUE, levels = likert_levels),
  ))
```

# Demographic characterisitics of the sample

## gender
```{r}
d_trustvac %>%
  count(gender_nb)

d_trustvac %>%
  ggplot(aes(x = gender_nb)) +
  geom_bar()
```
## age
```{r}
d_trustvac %>%
  summarise(
    n = n(),
    M = mean(age) %>% round(digits = 2),
    SD = sd(age)%>% round(digits = 2))

d_trustvac %>%
  ggplot(aes(x = age))+
  geom_histogram(binwidth =  5)
```

